[project]
name = "karman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dotenv>=0.9.9",
    "selenium>=4.27.1",
]

[tool.uv]
dev-dependencies = [
    "pyinstaller>=6.12.0",
]
